server:
  port: 8888

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://www.soyoung.dev:8690/pitch
    username: dev
    password: best2
  redis:
    port: 6379
    host: www.soyoung.dev
    password: 1323

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.server.pitch

logging:
  level:
    org.springframework.security: DEBUG

