server:
  port: 8888

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://www.soyoung.dev:8690/pitch
    username: dev
    password: best2
  redis:
    port: 6379
    host: www.soyoung.dev
    password: 1323
  profiles:
    include: oauth
  servlet:
    multipart:
      maxFileSize: 200MB
      maxRequestSize: 200MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.server.pitch

token:
  expiration_time: 86400000
  refreshToken_time: 604800000
  asecret: jwtAccess
  rsecret: jwtRefresh

email:
  user: xlor4528@gmail.com
  password: kycqtaqkiomgrjjr
  smtp_host: smtp.gmail.com
  smtp_port: 465
#logging:
#  level:
#    org.springframework.security: DEBUG
#    com.server.pitch.filter: DEBUG

